# Generated by Django 4.1.1 on 2022-10-28 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_remove_ocrtext_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfOcrText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploader.pdffile')),
            ],
        ),
    ]
