# Generated by Django 4.1.1 on 2022-10-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0003_pdfocrtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfocrtext',
            name='text',
            field=models.TextField(blank=True, verbose_name='PdfOcrText'),
        ),
    ]
